# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Bimmer Sticker Store
subtitle: We specialize on making vinyl stickers for BMW cars and other car makes. Shoot us an email for custom orders.
description: Handcrafted vinyl stickers for your BMW. Variety of designs for different models, series and generations. We offer free shipping across US.
keywords: bmw, sticker, car, vinyl, window, windshield, banner, orcacal
author: Petr Stepanov
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://bimmersticker.store # http://localhost:4000/
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMMM Do YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/

#theme: landscape
theme: blueberry

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

# Comments
comments: false

# Sitemap
sitemap:
  path: sitemap.xml
  tag: false
  category: false

# Configuration for hexo-image-sizes https://github.com/hexojs/hexo-filter-responsive-images
responsive_images:
  pattern: '**/*.+(png|jpg|jpeg)'
  sizes:
    small:
      width: 128
      height: 128

# Data file export
google_feed_path:
  src: source/_data/product_list.yml
  dest: product_list.txt

netlify_redirects_path:
  src: source/_redirects
  dest: _redirects

snipcart: false