# Header
logo: /img/bimmer-sticker-store-logo.svg

# Jumbotron
slogan: Handcrafted Stickers for Your Bimmer
lead: A quick vinyl upgrade that makes your BMW notably different.

# Default Meta
title: Bimmer Sticker Store
description: Handcrafted vinyl stickers for your BMW. Variety of designs for different models, series and generations. We offer free shipping across US.

# Miscellaneous
favicon: /favicon.ico
apple_touch_icon: /apple-touch-icon.png

# Social
facebook_url: https://www.facebook.com/bimmersticker.store/
instagram_url: https://www.instagram.com/bimmersticker.store/
email: info@bimmersticker.store
