# Header
logo: /img/bimmer-sticker-store-logo.svg

# Jumbotron
slogan: Handcrafted Vinyl Stickers for Your Car
lead: A quick vinyl upgrade that makes your vehicle notably different.

# Default Meta
title: Bimmer Sticker Store
description: Handcrafted vinyl stickers for your car. We specialize on BMW cars, but some stickers fit other cars as well. We offer variety of designs for different models, series and generations. Free US and affordable international shipping.

# Miscellaneous
favicon: /favicon.ico
apple_touch_icon: /apple-touch-icon.png

# Social
facebook_url: https://www.facebook.com/bimmersticker.store/
instagram_url: https://www.instagram.com/bimmersticker.store/
twitter_url: https://twitter.com/bimmersticker
email: "&#105;&#110;f%6f%40b&#105;%6dme%72st%69&#99;k%65r.%73tor%65"
formcarry_url: https://formcarry.com/s/2GJ-ONB1eLi
