banner:
  image: product-type-banner.jpg
  title: "Windshield Banner"
  price: 25.99
  description: "Place it on top or bottom."
  size: "Size is about 30×6 in."
sunstrip:
  image: product-type-sunstrip.jpg
  title: "Plain Sun Strip"
  price: 19.99
  description: "Cut it to fit the windshield."
  size: "Size is 60×11 in."
cutsunstrip:
  image: product-type-cut-sunstrip.jpg
  title: "Cutout Sun Strip"
  price: 34.99
  description: "Text is cut out of the base layer."
  size: "Size is 60×11 in."
textsunstrip:
  image: product-type-text-sunstrip.jpg
  title: "Text Sun Strip"
  price: 34.99
  description: "Text layer on top of the base strip."
  size:  "Size is 60×11 in."