# Google Merchant Instructions:
# We parse properties containing "|", for instance "size" or "color" and iterate over them.
# For each, we append '-#' to "id". And remain "item_group_id" equal to original "id"
#
# Snipcart instructions:
# In .ejs detect attributes with "|". 
# Set data-item-custom1-name="Frame color" to key name
# Set data-item-custom1-options="Black|Brown|Gold" to value
# for items with customization, define data-item-custom2-name="Your instagram name"
#
# MPN: Manufacturer Part Number - numbers and letters (can be id without dashes)
# GTIN: Global Trade Item Number
- id:	ST_BMW_ENGINE
  title: "Custom BMW Powered windshield sticker"
  description: "Custom BMW windshield sticker with wording 'Powered' and stripes. We make it for any engine model, you call it. Sticker is contour cut out of premium outdoor vinyls. Available in various colors."
  google_product_category: Care & Decor > Vehicle Decor > Bumper Stickers
  product_type: Stickers > BMW
  link: https://bimmersticker.store/custom-engine-windshield-sticker/
  image_link: https://bimmersticker.store/bimmer-not-beamer/bimmer-not-beamer-sticker.jpg
  condition: new
  availability: "in stock"
  price: "12.99 USD"
  mpn: STBMENG
  brand: "Bimmer Sticker Store"
  size: "24x4 in"
  shipping: "US::Standard:0 USD"
  weight: "0.2 lbs"
  color: "Glossy White|Matte Black|Oil Slick"
- id:	ST_BMW_BNB
  title: "Bimmer Not Beamer sticker"
  description: "Sticker is designed to tell them how to spell it right. Made of premium outdoor vinyl. Comes with easy installation instructions. Durability is about 5 years."
  google_product_category: Care & Decor > Vehicle Decor > Bumper Stickers
  product_type: Stickers > BMW
  link: https://bimmersticker.store/bimmer-not-beamer/
  image_link: https://bimmersticker.store/bimmer-not-beamer/bimmer-not-beamer-sticker.jpg
  condition: new
  availability: "in stock"
  price: "7.99 USD"
  mpn: "" # id without underscores
  item_group_id: "" # equal to id (if variations) or empty
  brand: "Bimmer Sticker Store"
  size: "7x2 in"
  shipping: "US::Standard:0 USD"
  weight: "0.06 lbs"
  color: "White/Red|Holographic/Red"
- id:	ST_SOCIAL_IG
  title: "Two custom Instagram name stickers"
  description: "A set of two custom stickers with your Instagram name (handle). Stickers are contour cut out of premium outdoor vinyls. Transparent background. Available in white or holographic color. Stickers come with installation instructions."
  google_product_category: Care & Decor > Vehicle Decor > Bumper Stickers
  product_type: Stickers > Social
  link: https://bimmersticker.store/bimmer-not-beamer/
  image_link: https://bimmersticker.store/bimmer-not-beamer/bimmer-not-beamer-sticker.jpg
  condition: new
  availability: "in stock"
  price: "7.99 USD"
  mpn: STBMBNB
  brand: "Bimmer Sticker Store"
  size: "7x2 in"
  shipping: "US::Standard:0 USD"
  weight: "0.06 lbs"